# Generated by Django 4.1.1 on 2022-11-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='room.cardroom'),
        ),
    ]
