# Generated by Django 4.1.1 on 2022-12-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='last_played_card',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
