# Generated by Django 4.1.1 on 2022-11-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_stats_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='old_board',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
