# Generated by Django 4.1.1 on 2022-11-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0003_alter_stats_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="end_of_line",
            field=models.BooleanField(default=1, verbose_name=False),
            preserve_default=False,
        ),
    ]
