# Generated by Django 4.1.1 on 2022-11-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0004_stats_old_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="cards_per_round",
            field=models.IntegerField(default=0),
        ),
    ]
