# Generated by Django 4.1.1 on 2022-11-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0004_stats_end_of_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stats",
            name="end_of_line",
            field=models.BooleanField(default=False),
        ),
    ]
