# Generated by Django 4.1.1 on 2022-12-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_stats_last_played_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='timer',
        ),
    ]
