# Generated by Django 4.1.1 on 2022-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0005_stats_cards_per_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="winner",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
