# Generated by Django 4.1.1 on 2022-12-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_stats_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='last_played_card',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
