# Generated by Django 4.1.1 on 2022-11-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0005_alter_stats_end_of_line"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stats",
            name="end_of_line",
        ),
    ]
