# Generated by Django 4.1.1 on 2022-12-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0006_alter_stats_last_played_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="p1_choice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stats",
            name="p2_choice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stats",
            name="p3_choice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stats",
            name="p4_choice",
            field=models.BooleanField(default=False),
        ),
    ]
