# Generated by Django 4.1.1 on 2022-12-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0010_cardroom_game_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardroom",
            name="status",
        ),
        migrations.RemoveField(
            model_name="stats",
            name="p1_choice",
        ),
        migrations.RemoveField(
            model_name="stats",
            name="p2_choice",
        ),
        migrations.RemoveField(
            model_name="stats",
            name="p3_choice",
        ),
        migrations.RemoveField(
            model_name="stats",
            name="p4_choice",
        ),
    ]
