# Generated by Django 4.1.1 on 2022-12-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0011_remove_cardroom_status_remove_stats_p1_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="p1_choice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stats",
            name="p2_choice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stats",
            name="p3_choice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stats",
            name="p4_choice",
            field=models.BooleanField(default=False),
        ),
    ]
