# Generated by Django 4.1.1 on 2022-12-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0013_remove_stats_p1_choice_remove_stats_p2_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="players_choice",
            field=models.IntegerField(default=0),
        ),
    ]
