# Generated by Django 4.1.1 on 2022-12-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0014_stats_players_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="cards_in_play",
            field=models.IntegerField(default=0),
        ),
    ]
