# Generated by Django 4.1.1 on 2023-02-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0016_cardroom_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardroom",
            name="room_opened",
            field=models.BooleanField(default=True),
        ),
    ]
