# Generated by Django 4.1.1 on 2023-02-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_cardroom_room_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardroom',
            name='view_rejoin',
            field=models.BooleanField(default=False),
        ),
    ]
