# Generated by Django 4.1.1 on 2023-03-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_cardroom_view_rejoin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardroom',
            name='status',
        ),
    ]
