# Generated by Django 4.1.1 on 2023-03-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_remove_cardroom_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardroom',
            name='seats',
        ),
    ]
