# Generated by Django 4.1.1 on 2023-03-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_remove_cardroom_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardroom',
            name='room_opened',
        ),
        migrations.RemoveField(
            model_name='cardroom',
            name='view_rejoin',
        ),
    ]
