# Generated by Django 4.1.1 on 2023-03-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0021_remove_cardroom_room_opened_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardroom',
            name='remaining_players',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
