# Generated by Django 4.1.1 on 2023-03-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0022_cardroom_remaining_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardroom',
            name='leaving_players',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
