# Generated by Django 4.1.1 on 2023-03-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0023_cardroom_leaving_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='players_choice',
        ),
    ]
