# Generated by Django 4.1.1 on 2023-03-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0024_remove_stats_players_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardroom',
            name='remaining_players',
        ),
    ]
