# Generated by Django 4.1.1 on 2023-03-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0027_cardroom_players_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardroom',
            name='players_count',
        ),
    ]
