# Generated by Django 4.1.1 on 2022-10-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_cardroom_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardroom',
            old_name='player_name',
            new_name='players',
        ),
        migrations.RemoveField(
            model_name='cardroom',
            name='status',
        ),
    ]
