# Generated by Django 4.1.1 on 2022-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='board',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='played_card',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='player_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='team_one_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='team_two_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='trump_card',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
