# Generated by Django 4.1.1 on 2022-10-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_stats_board_alter_stats_played_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='player_position',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='team_one_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='team_two_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
