# Generated by Django 4.1.1 on 2022-10-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_rename_player_name_cardroom_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardroom',
            name='started',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
