# Generated by Django 4.1.1 on 2022-10-20 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0003_rename_player_name_cardroom_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardroom',
            name='players',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
