# Generated by Django 4.1.1 on 2022-10-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_cardroom_players'),
        ('room', '0004_cardroom_started'),
    ]

    operations = [
    ]
