# Generated by Django 4.1.1 on 2022-10-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_cardroom_players_count_alter_cardroom_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardroom',
            name='players_count',
            field=models.IntegerField(default=0),
        ),
    ]
