# Generated by Django 4.1.1 on 2022-10-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_stats_player_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='player_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='team_one_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='team_two_score',
            field=models.IntegerField(default=0),
        ),
    ]
