# Generated by Django 4.1.1 on 2022-10-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_cardroom_players_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardroom',
            name='started',
            field=models.BooleanField(default=True),
        ),
    ]
