# Generated by Django 4.1.1 on 2022-10-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_cardroom_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardroom',
            old_name='started',
            new_name='status',
        ),
    ]
