# Generated by Django 4.1.1 on 2022-10-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='room.cardroom'),
            preserve_default=False,
        ),
    ]
