# Generated by Django 4.1.1 on 2022-10-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hand', models.CharField(max_length=50)),
                ('tricks', models.IntegerField()),
                ('played_cards', models.CharField(max_length=50)),
            ],
        ),
    ]
