# Generated by Django 4.1.1 on 2022-10-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=20)),
                ('trump_card', models.CharField(max_length=10)),
                ('team_one_score', models.IntegerField()),
                ('team_two_score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
