# Generated by Django 4.1.1 on 2022-10-17 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('whist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRoom',
            fields=[
                ('username', models.CharField(max_length=60)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
