# Generated by Django 4.1.1 on 2022-10-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0002_gamestats_player_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_position',
        ),
        migrations.AddField(
            model_name='gamestats',
            name='player_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
