# Generated by Django 4.1.1 on 2022-10-17 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whist', '0002_cardroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardroom',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cardroom',
            name='name',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardroom',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
