# Generated by Django 4.1.1 on 2022-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0003_remove_cardroom_user_id_cardroom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
