# Generated by Django 4.1.1 on 2022-10-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whist', '0004_gamestats_played_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestats',
            name='played_card',
            field=models.CharField(max_length=4),
        ),
    ]
