# Generated by Django 4.1.1 on 2023-01-27 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0003_alter_user_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
