# Generated by Django 4.1.1 on 2022-10-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userprofile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
