# Generated by Django 4.1.1 on 2023-01-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="default.png", upload_to="profile_avatars"),
        ),
    ]
