# Generated by Django 4.1.1 on 2022-10-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='played_hand',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tricks',
            field=models.IntegerField(default=0),
        ),
    ]
