# Generated by Django 4.1.1 on 2022-10-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_remove_user_nickname_user_hand_user_played_cards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='user',
            name='played_cards',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tricks',
        ),
    ]
