# Generated by Django 4.1.1 on 2022-10-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_rename_hands_user_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hand',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='played_hand',
            field=models.CharField(default='', max_length=80),
        ),
    ]
